CREATE database D2HDB;

USE D2HDB;

CREATE TABLE D2H_USERS(
    UID INT(3) PRIMARY KEY AUTO_INCREMENT,
    UNM VARCHAR(30) NOT NULL UNIQUE UNIQUE,
    PWD VARCHAR(10000) NOT NULL,
    ROLE VARCHAR(30) NOT NULL
);

CREATE TABLE CONSUMER(
    CSID INT PRIMARY KEY AUTO_INCREMENT,
    FNM VARCHAR(150) NOT NULL,
    LNM VARCHAR(150) NOT NULL,
    EML VARCHAR(200) NOT NULL,
    MBN CHAR(10) NOT NULL,
    DNO VARCHAR(20) NOT NULL,
    STRT VARCHAR(150) NOT NULL,
    CITY VARCHAR(150) NOT NULL,
    STATE VARCHAR(150) NOT NULL,
    WBAL VARCHAR(150) NOT NULL,
    UID INT REFERENCES D2H_USERS(UID)
);

CREATE TABLE CHANNEL_CATEGORIES(
    CTID INT PRIMARY KEY AUTO_INCREMENT,
    CTNM VARCHAR(200) NOT NULL,
    DSCP VARCHAR (1000)
);

CREATE TABLE CHANNELS(
    CHID INT PRIMARY KEY AUTO_INCREMENT,
    CHNM VARCHAR(200) NOT NULL,
    RATE NUMERIC NOT NULL,
    CTID INT REFERENCES CHANNEL_CATEGORIES(CTID)
);

CREATE TABLE PACKAGES(
    PKID INT PRIMARY KEY AUTO_INCREMENT,
    PKNM VARCHAR (150) NOT NULL,
    RATE NUMERIC NOT NULL
);

CREATE TABLE PACKAGE_DETAILS(
    PKID INT REFERENCES PACKAGES(PKID),
    CHID INT REFERENCES CHANNELS(CHID),
    PRIMARY KEY (PKID,CHID)
);

CREATE TABLE DISCOUNTS(
    DSID INT PRIMARY KEY AUTO_INCREMENT,
    PRCT NUMERIC NOT NULL,
    SDT DATE NOT NULL,
    EDT DATE NOT NULL,
    MAXC INT
);

CREATE TABLE SUBSCRIPTIONS(
    SRID INT PRIMARY KEY AUTO_INCREMENT,
    CSID INT REFERENCES CONSUMER(CSID),
    PKID INT REFERENCES PACKAGES(PKID),
    SDT DATE,
    EDT DATE,
    GTA NUMERIC,
    GST NUMERIC,
    DSAMT NUMERIC,
    NPA NUMERIC,
    DSID INT REFERENCES DISCOUNTS(DSID)
);

CREATE TABLE TRANSACTIONS(
    TXNID INT PRIMARY KEY AUTO_INCREMENT,
    AMT NUMERIC,
    TXNDT DATE,
    TTYPE INT,
    DSCP VARCHAR(150),
    CSID INT REFERENCES CONSUMER(CSID)
);